substitutions:
  _REGION: northamerica-northeast2
  _PROJECT_ID: delivery-api-451403
  _REPO_NAME: delivery-api-repo


steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/delivery-api-docker:latest'
      - '-t'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/delivery-api-docker:$COMMIT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/delivery-api-docker:latest'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/delivery-api-docker:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'delivery-api'
      - '--image'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/delivery-api-docker:latest'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      #- '--set-env-vars DATABASE_URL="mongodb+srv://sidd58:Naruto58@cluster-1.ywzro.mongodb.net/deliveryDB?retryWrites=true&w=majority&appName=Cluster-1",PORT=8080'
images:
  - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/delivery-api-docker:latest'
  - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/delivery-api-docker:$COMMIT_SHA'

options:
  logging: 'CLOUD_LOGGING_ONLY'
